import re

path = r"C:\Users\81804\OneDrive\デスクトップ\auto-affiliate-blog-main\generate.py"
with open(path, encoding="utf-8") as f:
    src = f.read()

NEW_PRODUCTS = r"""
    # 追加製品バッチ2
    # ゲーミング追加
    {"slug":"review-asusrogallyX","name":"ASUS ROG Ally X","cat":"ゲーミング","emoji":"🎮","price":"¥119,800","score":4.7,"bg":"#1a1a2e,#2d1b69","scores":[("ゲーム性能",96,4.8),("ディスプレイ",94,4.7),("携帯性",90,4.5),("バッテリー",82,4.1),("コスパ",80,4.0)],"specs":[("CPU/GPU","AMD Ryzen Z1 Extreme"),("RAM","24GB LPDDR5"),("ストレージ","1TB NVMe SSD"),("ディスプレイ","7インチ FHD 120Hz"),("バッテリー","80Wh"),("重量","678g")],"pros":["Z1 Extremeの圧倒的なAPU性能","120Hz FHDディスプレイが滑らか","24GBメモリでゲーム＋バックグラウンドも余裕","Windows 11でPC全ゲームが遊べる","外付けGPU（XG Mobile）拡張対応"],"cons":["12万円","678gと携帯ゲーム機より重い","バッテリーが2〜3時間（ゲーム時）","発熱管理が必要"],"desc":"PCゲームを持ち歩ける革命的デバイス。Steam・Epic・Xbox全部遊べるWindows PCがコントローラー付きで手のひらに。出張先のホテルでも本格ゲームが可能。","related":[("review-nintendoswitch2","🎮","ゲーミング","Nintendo Switch 2 レビュー",4.8),("review-ps5slim","🎮","ゲーミング","PlayStation 5 Slim レビュー",4.7),("review-xboxseriesx","🎮","ゲーミング","Xbox Series X レビュー",4.6)]},
    {"slug":"review-logicoolG502X","name":"Logicool G502 X Plus","cat":"ゲーミング","emoji":"🎮","price":"¥16,980","score":4.6,"bg":"#0d1b2a,#1b263b","scores":[("センサー精度",100,5.0),("ボタン配置",96,4.8),("重量調整",96,4.8),("バッテリー",90,4.5),("コスパ",88,4.4)],"specs":[("センサー","HERO 25K（最大25,600DPI）"),("接続","LIGHTSPEED / Bluetooth / 有線"),("重量","106g（最軽量時）"),("バッテリー","最大130時間"),("ボタン","13個プログラマブル"),("特徴","HYPERTENSIONバネ式クリック")],"pros":["HERO 25Kセンサーが業界最高精度","HYPERTENSIONクリックの超軽量クリック感","130時間バッテリーで充電を忘れられる","重量調整ウェイト付属","FPS・MOBA両方に最適"],"cons":["1.7万円","右手専用（左利きNG）","有線版より重い"],"desc":"FPSプロゲーマーが選ぶ最強マウス。HERO 25Kセンサーは照準の精度を限界まで高める。130時間バッテリーとHYPERTENSIONクリックで長時間プレイが快適。","related":[("review-logicoolGProXSuperlight2","🎮","ゲーミング","Logicool G Pro X Superlight 2 レビュー",4.8),("review-razerdeathadder","🎮","ゲーミング","Razer DeathAdder V3 レビュー",4.6),("review-steelseriesarctisnova","🎮","ゲーミング","SteelSeries Arctis Nova Pro レビュー",4.7)]},
    {"slug":"review-corsairK100air","name":"Corsair K100 Air Wireless","cat":"ゲーミング","emoji":"🎮","price":"¥29,800","score":4.5,"bg":"#1a0a0a,#2d1515","scores":[("キー品質",96,4.8),("ワイヤレス遅延",100,5.0),("バックライト",96,4.8),("バッテリー",88,4.4),("コスパ",80,4.0)],"specs":[("スイッチ","CORSAIR MLX Ultra-Low Profile"),("接続","SLIPSTREAM WIRELESS / Bluetooth / 有線"),("バックライト","RGB 16.8M色"),("バッテリー","200時間（バックライトオフ）"),("遅延","1ms ワイヤレス"),("重量","810g")],"pros":["SLIPSTREAM 1msワイヤレスは有線と遅延差ゼロ","200時間バッテリーで実質充電不要","Ultra-Low Profileキーで打鍵感が軽快","iCUEで全キー細かくプログラム","キーボード＋マウスのワイヤレス化で机がスッキリ"],"cons":["3万円","810gの重さ","Ultra-Low Profileの打鍵感が好みを分ける"],"desc":"ゲーミングキーボードのワイヤレス最高峰。1ms遅延で有線と体感差ゼロ、200時間バッテリーは圧倒的。机上をケーブルフリーにしたいゲーマーへ。","related":[("review-keychronk2pro","⌨️","PC周辺機器","Keychron K2 Pro レビュー",4.6),("review-logicoolG502X","🎮","ゲーミング","Logicool G502 X Plus レビュー",4.6),("review-steelseriesarctisnova","🎮","ゲーミング","SteelSeries Arctis Nova Pro レビュー",4.7)]},
    # PC周辺機器追加
    {"slug":"review-sonyinzone-m9ii","name":"Sony INZONE M9 II","cat":"PC周辺機器","emoji":"🖥️","price":"¥128,800","score":4.7,"bg":"#0d0221,#1a0a3a","scores":[("4K OLED",100,5.0),("ゲーム機能",96,4.8),("PS5連携",100,5.0),("応答速度",98,4.9),("コスパ",76,3.8)],"specs":[("パネル","WOLED 4K 144Hz"),("サイズ","27インチ"),("応答速度","0.03ms GtG"),("接続","HDMI 2.1×2 / DP 1.4×1"),("特徴","PS5 Auto HDR Tone Mapping / 1ms"),("スピーカー","内蔵2.5W×2")],"pros":["0.03ms GTGの超高速応答でゲームが超滑らか","PS5 Auto HDR Tone Mappingで自動最適化","WOLED 4Kの圧倒的画質","HDMI 2.1×2でPS5+PC同時接続","Sony INZONE ヘッドセットとの連携"],"cons":["13万円","27インチのみ","スピーカーは最低限"],"desc":"PS5ゲーマーのための最強モニター。0.03msとPS5最適化機能がゲーム体験を別次元に引き上げる。PS5持ちなら最高の選択肢。","related":[("review-dellalienware34oled","🖥️","モニター","Dell Alienware 34 OLED レビュー",4.8),("review-asusrogswiftpg279qm","🖥️","モニター","ASUS ROG Swift PG279QM レビュー",4.6),("review-ps5slim","🎮","ゲーミング","PlayStation 5 Slim レビュー",4.7)]},
    {"slug":"review-elgatovave","name":"Elgato Wave DX","cat":"PC周辺機器","emoji":"🎙️","price":"¥19,800","score":4.5,"bg":"#1a1a2e,#2d2d5e","scores":[("音質",92,4.6),("コスパ",92,4.6),("ノイズ除去",90,4.5),("設置のしやすさ",88,4.4),("配信向け",94,4.7)],"specs":[("方式","ダイナミックマイク（XLR）"),("周波数","50Hz〜20kHz"),("感度","-51dBV/Pa"),("接続","XLR（Wave XLRドック対応）"),("重量","316g"),("特徴","心臓部：ダイナミック×Wave Link")],"pros":["ダイナミック収音で周囲の音を拾わない","Wave XLRドックでUSBプラグ＆プレイ","Wave Linkで複数音源のミキシング","2万円のコスパ","Elgatoエコシステムとの親和性"],"cons":["XLRのため単体ではPCに直接接続不可","Blue Yeti XほどのUSB直結の手軽さはない","コンデンサーより音の太さが控えめ"],"desc":"配信・在宅ワークの音声品質を劇的に改善するダイナミックマイク。背景ノイズを拾わない特性がゲーム配信・会議に最適。Elgatoエコシステムと組み合わせると更に輝く。","related":[("review-blueyetix","🎙️","PC周辺機器","Blue Yeti X レビュー",4.6),("review-elgatocamlink4k","🎙️","PC周辺機器","Elgato Cam Link 4K レビュー",4.5),("review-elgatostreamdeck","🎮","ゲーミング","Elgato Stream Deck MK.2 レビュー",4.5)]},
    {"slug":"review-logicoolmxbrio4k","name":"Logicool MX Brio 4K","cat":"PC周辺機器","emoji":"📷","price":"¥27,980","score":4.6,"bg":"#1b5e20,#2e7d32","scores":[("映像品質",98,4.9),("AI背景処理",96,4.8),("コスパ",86,4.3),("接続性",90,4.5),("対応OS",92,4.6)],"specs":[("解像度","4K 30fps / 1080p 60fps"),("視野角","90°"),("AI","AI顔追跡・背景ブラー"),("接続","USB-C / USB-A"),("対応","Windows / macOS / Chrome OS"),("特徴","Logicool AI仮想背景")],"pros":["4K解像度でテレビ会議の映像が激変","AI顔追跡で動いても常にフレームに入る","AI仮想背景が自然できれい","USB-C×USB-A両対応","Teams・Zoom認定"],"cons":["2.8万円","4K 60fps非対応（30fpsまで）","AIの顔追跡は動き方による"],"desc":"テレワークの第一印象を変えるWebカメラ。4K×AIで映像品質が圧倒的に向上し、会議での印象が劇的に変わる。フルタイムリモートワーカーへの最優先投資。","related":[("review-elgatocamlink4k","📷","PC周辺機器","Elgato Cam Link 4K レビュー",4.5),("review-blueyetix","🎙️","PC周辺機器","Blue Yeti X レビュー",4.6),("review-jabra-evolve2buds","🎧","ワイヤレスイヤホン","Jabra Evolve2 Buds レビュー",4.5)]},
    # タブレット追加
    {"slug":"review-ipadprom413inch","name":"iPad Pro M4 13インチ","cat":"タブレット","emoji":"📟","price":"¥218,800","score":4.8,"bg":"#1a1a2e,#16213e","scores":[("OLED画質",100,5.0),("M4性能",100,5.0),("薄さ",100,5.0),("Apple Pencil Pro",98,4.9),("コスパ",72,3.6)],"specs":[("チップ","M4"),("ディスプレイ","13インチ Ultra Retina XDR OLED"),("厚さ","5.1mm（世界最薄）"),("重量","582g"),("Apple Pencil","Pro対応"),("接続","Thunderbolt 4 / Wi-Fi 6E")],"pros":["5.1mmという非常識な薄さ","M4チップでMacBook Pro 14と同等性能","Ultra Retina XDR OLEDの圧倒的画質","Apple Pencil Proの触感フィードバック","Thunderbolt 4で4Kモニター出力可"],"cons":["22万円","Magic Keyboard別売りでPC化に追加費用","重量は582gあるため長時間持つのは辛い"],"desc":"コンピューターの概念を変える13インチOLEDタブレット。5.1mmの薄さとM4の性能は他の追随を許さない。クリエイターがMacBookの代わりに選ぶ時代が来た。","related":[("review-ipadprom4","📟","タブレット","iPad Pro M4 11インチ レビュー",4.7),("review-ipadairm2","📟","タブレット","iPad Air M2 レビュー",4.5),("review-galaxytabs10ultra","📟","タブレット","Galaxy Tab S10 Ultra レビュー",4.6)]},
    {"slug":"review-galaxytabs10FE","name":"Samsung Galaxy Tab S10 FE","cat":"タブレット","emoji":"📟","price":"¥79,800","score":4.3,"bg":"#1a237e,#283593","scores":[("コスパ",92,4.6),("S Pen",100,5.0),("画面サイズ",90,4.5),("性能",80,4.0),("バッテリー",88,4.4)],"specs":[("チップ","Exynos 1580"),("ディスプレイ","10.9インチ TFT LCD 90Hz"),("S Pen","付属"),("バッテリー","10,090mAh"),("重量","523g"),("接続","Wi-Fi 6 / 5G対応モデルあり")],"pros":["S Pen付属で8万円のコスパ","10,090mAhの大容量バッテリー","90Hzで動作が滑らか","Galaxy AIの一部機能対応","10.9インチの大画面"],"cons":["LCD（OLEDではない）","Exynos 1580はミドルレンジ","Tab S10 Ultraに劣る仕上がり感"],"desc":"S Penを8万円で入手できるGalaxyタブレット入門機。手書きメモ・スケッチが標準機能として使えるコスパは国内最高水準。学生・ビジネスマンに最適。","related":[("review-galaxytabs10ultra","📟","タブレット","Galaxy Tab S10 Ultra レビュー",4.6),("review-ipadairm2","📟","タブレット","iPad Air M2 レビュー",4.5),("review-ipadprom4","📟","タブレット","iPad Pro M4 レビュー",4.7)]},
    # スマートウォッチ追加
    {"slug":"review-applewatchseries10","name":"Apple Watch Series 10 46mm","cat":"スマートウォッチ","emoji":"⌚","price":"¥62,800","score":4.7,"bg":"#1a1a2e,#16213e","scores":[("健康機能",96,4.8),("薄さ",100,5.0),("睡眠追跡",96,4.8),("Apple連携",100,5.0),("コスパ",80,4.0)],"specs":[("ディスプレイ","46mm LTPO OLED Always-On"),("チップ","S10"),("薄さ","9.7mm（過去最薄）"),("センサー","心拍・血中酸素・水温・睡眠無呼吸検知"),("防水","50m防水"),("特徴","睡眠時無呼吸症候群検知（新機能）")],"pros":["睡眠時無呼吸症候群検知が追加（世界初）","9.7mmの過去最薄設計","水温センサーで海・プール対応","LTPO Always-Onで常時表示","iPhoneユーザーに最も統合された体験"],"cons":["6.3万円","Android非対応","バッテリーは18〜36時間（競合に劣る）"],"desc":"睡眠時無呼吸症候群を検知できるようになった最新Apple Watch。9.7mmの薄さと健康管理機能の充実度でiPhoneユーザーの最高の相棒に。","related":[("review-applewatchs10","⌚","スマートウォッチ","Apple Watch S10 レビュー",4.6),("review-applewatchultra2","⌚","スマートウォッチ","Apple Watch Ultra 2 レビュー",4.8),("review-galaxywatch7","⌚","スマートウォッチ","Galaxy Watch 7 レビュー",4.5)]},
    {"slug":"review-garminvivomove5","name":"Garmin Vívomove Sport","cat":"スマートウォッチ","emoji":"⌚","price":"¥28,800","score":4.2,"bg":"#1b5e20,#2e7d32","scores":[("デザイン",98,4.9),("健康追跡",86,4.3),("コスパ",90,4.5),("バッテリー",88,4.4),("アナログ感",100,5.0)],"specs":[("デザイン","アナログ時計×隠しディスプレイ"),("センサー","心拍・ストレス・血中酸素"),("バッテリー","最大5日"),("防水","5ATM"),("接続","Bluetooth"),("特徴","隠れたデジタルディスプレイ")],"pros":["アナログ時計に見えるスマートウォッチ","職場でも使えるビジネス対応デザイン","2.9万円のコスパ","5ATM防水","Garmin Connectとの連携"],"cons":["Garmin上位機より健康機能が少ない","ディスプレイが小さく情報量が少ない","GPS非内蔵"],"desc":"スマートウォッチを着けていると思われたくない人のための一台。アナログ時計の見た目でスマートウォッチ機能を隠し持つ。ビジネスシーンでも完全に馴染む。","related":[("review-garminvenu3","⌚","スマートウォッチ","Garmin Venu 3 レビュー",4.5),("review-withingsscanwatch2","⌚","スマートウォッチ","Withings ScanWatch 2 レビュー",4.5),("review-amazfitgtr4","⌚","スマートウォッチ","Amazfit GTR 4 レビュー",4.2)]},
    # ノートPC追加
    {"slug":"review-asuszenbook14oled","name":"ASUS Zenbook 14 OLED","cat":"ノートPC","emoji":"💻","price":"¥149,800","score":4.6,"bg":"#1a237e,#283593","scores":[("OLED画質",100,5.0),("コスパ",88,4.4),("軽量性",90,4.5),("バッテリー",86,4.3),("性能",90,4.5)],"specs":[("CPU","AMD Ryzen 7 8840HS"),("ディスプレイ","14インチ 2.8K OLED 120Hz"),("RAM","16GB LPDDR5X"),("SSD","512GB NVMe"),("重量","1.2kg"),("バッテリー","最大15時間")],"pros":["15万円で14インチ2.8K OLED×120Hz","1.2kgの軽量","OLEDで映画・写真編集が圧倒的に美しい","Ryzen 7 8840HSの高性能NPU（AI機能）","15時間バッテリー"],"cons":["512GBは拡張が限られる","AMD GPUは一部ソフトで動作確認必要","冷却がやや弱い（連続高負荷時）"],"desc":"15万円でOLEDディスプレイとRyzen 7を両立したコスパ最強ノートPC。写真・動画編集からビジネス用途まで。OLEDの美しさは一度使うと戻れない。","related":[("review-macbookairm3","💻","ノートPC","MacBook Air M3 レビュー",4.7),("review-dellxps15","💻","ノートPC","Dell XPS 15 レビュー",4.7),("review-hpspectrex360","💻","ノートPC","HP Spectre x360 レビュー",4.6)]},
    {"slug":"review-lenovo-yoga9i","name":"Lenovo Yoga 9i Gen 9","cat":"ノートPC","emoji":"💻","price":"¥179,800","score":4.5,"bg":"#212121,#424242","scores":[("2-in-1設計",100,5.0),("ディスプレイ",96,4.8),("音質",98,4.9),("バッテリー",90,4.5),("コスパ",78,3.9)],"specs":[("CPU","Intel Core Ultra 7 155H"),("ディスプレイ","14インチ OLED 2.8K タッチ"),("RAM","16GB"),("音声","Bose スピーカー×4"),("重量","1.35kg"),("特徴","360°ヒンジ / ペン付属")],"pros":["360°ヒンジでタブレットとして使える","Bose 4スピーカーがノートPC最高水準の音質","OLED 2.8Kタッチディスプレイ","ペン付属で手書き入力即対応","デザインが洗練されている"],"cons":["18万円","1.35kgはビジネスモバイルでは重め","Core Ultra 7は高負荷で発熱"],"desc":"タブレットにもなるプレミアムノートPC。BoseスピーカーとOLEDの組み合わせは他社の追随を許さない。音楽・映画・創作活動に理想の相棒。","related":[("review-hpspectrex360","💻","ノートPC","HP Spectre x360 レビュー",4.6),("review-macbookairm3","💻","ノートPC","MacBook Air M3 レビュー",4.7),("review-surfacepro11","📟","タブレット","Surface Pro 11 レビュー",4.4)]},
    # スマートフォン追加2
    {"slug":"review-googlepixel9proXL","name":"Google Pixel 9 Pro XL","cat":"スマートフォン","emoji":"📱","price":"¥189,900","score":4.8,"bg":"#1a237e,#283593","scores":[("AI機能",100,5.0),("カメラ",98,4.9),("バッテリー",94,4.7),("Tensor G4",92,4.6),("コスパ",76,3.8)],"specs":[("ディスプレイ","6.8インチ LTPO OLED 1〜120Hz"),("チップ","Google Tensor G4"),("カメラ","50MP+48MP超広角+48MP 5倍望遠"),("バッテリー","5,060mAh 37W"),("重量","221g"),("AI","Google AI Overviews / Gemini統合")],"pros":["Gemini AI統合で最も賢いAndroid","5060mAhで1日以上安心","カメラが全シーン最強クラス（6.8インチモデル）","最長7年のOS・セキュリティアップデート","Pixel Dropsで機能が増え続ける"],"cons":["19万円","Tensor G4は発熱が課題","5倍以上のズームはiPhone 16 Pro Maxに劣る"],"desc":"GoogleのAI能力が最大限発揮される最高峰Pixel。Gemini統合×7年更新保証は他のAndroidが追いつけない強み。AI機能を活用したいならPixel 9 Pro XL。","related":[("review-pixel9pro","📱","スマートフォン","Google Pixel 9 Pro レビュー",4.7),("review-iphone16promax","📱","スマートフォン","iPhone 16 Pro Max レビュー",4.9),("review-galaxys25ultra","📱","スマートフォン","Samsung Galaxy S25 Ultra レビュー",4.8)]},
    {"slug":"review-iphone16promaxnatural","name":"iPhone 16 Pro 256GB","cat":"スマートフォン","emoji":"📱","price":"¥159,800","score":4.8,"bg":"#2d2d2d,#3d3d3d","scores":[("カメラ",98,4.9),("A18 Pro",100,5.0),("コンパクト性",90,4.5),("バッテリー",90,4.5),("コスパ",76,3.8)],"specs":[("ディスプレイ","6.3インチ Super Retina XDR 120Hz"),("チップ","A18 Pro（3nm）"),("カメラ","48MP+48MP+5倍光学ズーム"),("バッテリー","最大27時間"),("重量","199g"),("特徴","カメラコントロール / ProRes 4K 120fps")],"pros":["Pro Maxと同じカメラ・チップで199g","6.3インチはPro Maxより片手操作しやすい","ProRes 4K 120fpsの動画が撮れる","チタン素材の高級感","Pro Maxより3.5万円安い"],"cons":["16万円","バッテリーはPro Maxに劣る","USB-Cは3.0（Pro Max同様）"],"desc":"Pro Maxと同じカメラ・チップを199gに収めた最強コンパクトiPhone Pro。Pro Maxは大きすぎると感じる人のベストアンサー。性能は全く妥協なし。","related":[("review-iphone16promax","📱","スマートフォン","iPhone 16 Pro Max レビュー",4.9),("review-iphone16","📱","スマートフォン","iPhone 16 レビュー",4.5),("review-pixel9pro","📱","スマートフォン","Google Pixel 9 Pro レビュー",4.7)]},
    {"slug":"review-xiaomi15","name":"Xiaomi 15","cat":"スマートフォン","emoji":"📱","price":"¥129,800","score":4.7,"bg":"#ff6d00,#1a1a1a","scores":[("コスパ",96,4.8),("カメラ",96,4.8),("Snapdragon 8 Elite",100,5.0),("充電速度",96,4.8),("バッテリー",90,4.5)],"specs":[("チップ","Snapdragon 8 Elite"),("カメラ","50MP×3（Leica共同開発）"),("充電","90W有線 + 50Wワイヤレス"),("バッテリー","5,240mAh"),("重量","190g"),("特徴","Leica Summilux光学系")],"pros":["Leica共同開発カメラが写真をアート作品に","90Wで40分フル充電","Snapdragon 8 Eliteで最強性能","5,240mAhで2日使える","13万円でフラッグシップ全部入り"],"cons":["グローバルモデルで日本語サポートが限定的","Leica効果は使い方に依存","Google標準より独自UIの使い勝手が好み分かれる"],"desc":"Leicaカメラ×Snapdragon 8 Elite×90Wを13万円で実現した価格破壊フラッグシップ。写真を芸術的に撮りたい人にとってXiaomi 15は最高の相棒。","related":[("review-xiaomi14ultra","📱","スマートフォン","Xiaomi 14 Ultra レビュー",4.7),("review-oppofindx8pro","📱","スマートフォン","OPPO Find X8 Pro レビュー",4.5),("review-oneplus13","📱","スマートフォン","OnePlus 13 レビュー",4.6)]},
    # カメラ追加
    {"slug":"review-omSystem-OM5","name":"OM SYSTEM OM-5 Mark II","cat":"カメラ","emoji":"📷","price":"¥119,800","score":4.5,"bg":"#1a237e,#283593","scores":[("防塵防滴",100,5.0),("手ブレ補正",100,5.0),("コンパクト性",96,4.8),("画質",86,4.3),("コスパ",82,4.1)],"specs":[("センサー","マイクロフォーサーズ 2037万画素"),("手ブレ補正","最大7.5段（ボディ内）"),("防塵防滴","IP53（マイナス10℃耐低温）"),("重量","414g"),("連写","最大30コマ/秒"),("特徴","野生動物AF / 最大240コマ高解像度合成")],"pros":["IP53防塵防滴でマイナス10℃まで対応","7.5段手ブレ補正で夜景手持ち可能","414gの超軽量","野生動物・乗り物AFの精度が高い","OM SYSTEMの山岳・アウトドア向け設計"],"cons":["マイクロフォーサーズはフルサイズより高感度が劣る","動画は4K 30fps止まり","12万円は競合比でやや高め"],"desc":"アウトドア・旅行カメラの最高峰。IP53防塵防滴でマイナス10℃まで動作し、7.5段手ブレ補正で激しい環境でも撮り逃しゼロ。山岳カメラマンの愛機。","related":[("review-fujifilmx100vi","📷","カメラ","Fujifilm X100VI レビュー",4.9),("review-fujifilmxt5","📷","カメラ","Fujifilm X-T5 レビュー",4.8),("review-goprohero13black","📷","カメラ","GoPro HERO13 Black レビュー",4.6)]},
    # スピーカー追加
    {"slug":"review-marshallEmberton3","name":"Marshall Emberton III","cat":"スピーカー","emoji":"🔊","price":"¥19,800","score":4.4,"bg":"#1a1a0a,#2a2a0a","scores":[("デザイン",100,5.0),("音質",88,4.4),("防水",94,4.7),("コスパ",90,4.5),("バッテリー",86,4.3)],"specs":[("出力","5W×2（ステレオ）"),("防水","IP67"),("バッテリー","最大30時間"),("接続","Bluetooth 5.3"),("重量","700g"),("特徴","ロック感あふれるクラシックデザイン")],"pros":["30時間バッテリーが圧倒的","Marshallのヴィンテージデザインがインテリアになる","IP67で屋外・風呂でも使える","ステレオ出力で左右の分離感","2万円のコスパ"],"cons":["700gはポータブルとして重め","低音はSONY XB43より控えめ","Bluetooth 5.3のみ（Wi-Fi非対応）"],"desc":"音楽と一緒に生きるブランドMarshallのポータブルスピーカー。30時間バッテリーとヴィンテージデザインがインテリアと音楽生活を同時に格上げする。","related":[("review-jblflip6","🔊","スピーカー","JBL Flip 6 レビュー",4.5),("review-boseSoundLinkMax","🔊","スピーカー","Bose SoundLink Max レビュー",4.7),("review-sonysrsxb43","🔊","スピーカー","Sony SRS-XB43 レビュー",4.5)]},
    # ワイヤレスイヤホン追加
    {"slug":"review-bose-ultra-earbuds","name":"Bose Ultra Open Earbuds","cat":"ワイヤレスイヤホン","emoji":"🎧","price":"¥39,600","score":4.5,"bg":"#1b5e20,#2e7d32","scores":[("開放感",100,5.0),("音質",86,4.3),("オープンイヤー安全性",100,5.0),("コスパ",78,3.9),("装着感",92,4.6)],"specs":[("方式","オープンイヤー（耳をふさがない）"),("再生時間","7時間（ケース含48時間）"),("防水","IPX4"),("接続","Bluetooth 5.3"),("重量","8.2g"),("特徴","OpenAudio技術")],"pros":["耳をふさがないので外音が聞こえる安全性","Boseの音質クォリティをオープンで実現","48時間ケース込みバッテリー","独自クリップで耳に安定装着","通話しながら外音が聞こえる自然な体験"],"cons":["4万円","音漏れがある（公共の場で注意）","ANCなし（オープンイヤーの仕様上）"],"desc":"耳をふさがない新体験を4万円で。外の音が聞こえるオープンイヤーはランニング・オフィス・育児に最適。Boseの音質でオープンイヤー市場を塗り替えた一台。","related":[("review-shokzOpenRunPro2","🎧","ワイヤレスイヤホン","Shokz OpenRun Pro 2 レビュー",4.4),("review-airpods-pro2","🎧","ワイヤレスイヤホン","AirPods Pro 2 レビュー",4.8),("review-boseqcearbuds2","🎧","ワイヤレスイヤホン","Bose QC Earbuds II レビュー",4.6)]},
    {"slug":"review-sony-wf1000xm5-sport","name":"Sony WF-SP910N","cat":"ワイヤレスイヤホン","emoji":"🎧","price":"¥18,980","score":4.3,"bg":"#006064,#00838f","scores":[("スポーツ向け",96,4.8),("ANC",84,4.2),("防水",96,4.8),("コスパ",90,4.5),("音質",82,4.1)],"specs":[("ANC","対応"),("防水","IPX4（スポーツ向け）"),("再生時間","9時間（ANCオン）"),("接続","Bluetooth 5.0"),("重量","6.5g"),("特徴","Sony 360 Reality Audio部分対応")],"pros":["IPX4でジムのシャワーでも安心","1.9万円のコスパ","ANC対応でトレーニングに集中","ソニーの安心品質","フィット感がスポーツ時に安定"],"cons":["フラッグシップWF-1000XM5より音質が劣る","ANCはWF-1000XM5に大差をつけられる","デザインがスポーティで普段使いに合わないことも"],"desc":"ジム・ランニング・スポーツ専用ならこれで完結。IPX4防水×ANC×ソニー品質で2万円以下という圧倒的コスパ。汗・水に強いスポーツイヤホンの定番。","related":[("review-shokzOpenRunPro2","🎧","ワイヤレスイヤホン","Shokz OpenRun Pro 2 レビュー",4.4),("review-sonywf1000xm5","🎧","ワイヤレスイヤホン","Sony WF-1000XM5 レビュー",4.8),("review-ankerliberty4nc","🎧","ワイヤレスイヤホン","Anker Liberty 4 NC レビュー",4.5)]},
    # モニター追加
    {"slug":"review-asusproadart27","name":"ASUS ProArt PA27UCX-K 27インチ","cat":"モニター","emoji":"🖥️","price":"¥198,000","score":4.7,"bg":"#1a237e,#283593","scores":[("色精度",100,5.0),("HDR",100,5.0),("クリエイター向け",100,5.0),("コスパ",72,3.6),("接続性",96,4.8)],"specs":[("パネル","IPS 4K 60Hz"),("色域","DCI-P3 99% / Adobe RGB 99%"),("HDR","DisplayHDR 1000（True Black）"),("キャリブレーション","ハードウェアキャリブレーション対応"),("接続","Thunderbolt 3×2 / HDMI 2.0×2"),("特徴","Delta E < 2 の出荷時校正済み")],"pros":["Delta E <2の出荷時色校正済み","DCI-P3 99%×Adobe RGB 99%×DisplayHDR 1000","ハードウェアキャリブレーション対応","Thunderbolt 3×2でMacとの連携が完璧","写真・映像・印刷に完璧な色再現"],"cons":["20万円","4K 60Hz（ゲーム向きではない）","重量が重い"],"desc":"プロフォトグラファー・映像クリエイターの最高峰モニター。出荷時の色校正済みでキャリブレーション不要から即戦力。色で妥協できない人への究極の答え。","related":[("review-benqpd3205u","🖥️","モニター","BenQ PD3205U レビュー",4.6),("review-lgultrafine5k27md5kl","🖥️","モニター","LG UltraFine 5K レビュー",4.6),("review-dellalienware34oled","🖥️","モニター","Dell Alienware 34 OLED レビュー",4.8)]},
"""

src = src.replace(
    '    {"slug":"review-boseqc45"',
    NEW_PRODUCTS + '    {"slug":"review-boseqc45"',
    1
)

with open(path, "w", encoding="utf-8") as f:
    f.write(src)

print("Done! batch 2 added.")
