import re

path = r"C:\Users\81804\OneDrive\デスクトップ\auto-affiliate-blog-main\generate.py"

NEW_PRODUCTS = '''    # --- 追加18製品 (200製品達成) ---
    {"slug":"review-jabra-evolve2buds","name":"Jabra Evolve2 Buds","cat":"ワイヤレスイヤホン","emoji":"🎧","price":"¥34,980","score":4.5,"bg":"#0a3d62,#1e6091","scores":[("通話品質",100,5.0),("ANC",92,4.6),("装着感",90,4.5),("バッテリー",86,4.3),("コスパ",82,4.1)],"specs":[("ANC","6マイク ハイブリッドANC"),("再生時間","6時間（ANCオン）/ ケース込み27時間"),("防水","IP57（シャワーOK）"),("接続","Bluetooth 5.2 / USB-Aドングル"),("特徴","Certified for Teams / Zoom / Google Meet"),("重量","5.8g")],"pros":["6マイクのビジネス最強通話品質","Microsoft Teams・Zoom認定取得","IP57で汗・水に完全対応","USB-Aドングルで安定ワイヤレス","ハイブリッドANCで集中力UP"],"cons":["3.5万円","再生時間は6時間とやや短め","音楽用途はAirPods Proに劣る","スポーツ向けデザインではない"],"desc":"ビジネスパーソンのための究極ワイヤレスイヤホン。Teams・Zoom認定の6マイク通話品質は他の追随を許さない。テレワーク・出張での通話品質を劇的改善する。","related":[("review-airpods-pro2","🎧","ワイヤレスイヤホン","AirPods Pro 2 レビュー",4.8),("review-sonywf1000xm5","🎧","ワイヤレスイヤホン","Sony WF-1000XM5 レビュー",4.8),("review-boseqcearbuds2","🎧","ワイヤレスイヤホン","Bose QC Earbuds II レビュー",4.6)]},
    {"slug":"review-shokzOpenRunPro2","name":"Shokz OpenRun Pro 2","cat":"ワイヤレスイヤホン","emoji":"🎧","price":"¥23,880","score":4.4,"bg":"#1b5e20,#2e7d32","scores":[("骨伝導音質",96,4.8),("装着安定性",100,5.0),("外音認識",100,5.0),("バッテリー",90,4.5),("コスパ",88,4.4)],"specs":[("方式","第10世代骨伝導"),("再生時間","12時間"),("充電","10分で1.5時間（急速充電）"),("防水","IP55"),("接続","Bluetooth 5.3"),("重量","30g")],"pros":["耳をふさがず外音が完全に聞こえる","ランニング・サイクリングに最適な安全性","12時間バッテリーで長距離でも安心","10分急速充電で1.5時間使える","超軽量30gで長時間装着も快適"],"cons":["音漏れあり（静かな場所で注意）","ANCなし（オープン型の仕様）","一般的なイヤホンより音質の迫力は控えめ","防水はIP55のみ（防塵は限定的）"],"desc":"スポーツと安全を両立する骨伝導イヤホンのベストセラー。耳をふさがないから車の音や周囲の状況が聞こえ、ランニング中も安全。12時間×急速充電で実用性も最強。","related":[("review-bose-ultra-earbuds","🎧","ワイヤレスイヤホン","Bose Ultra Open Earbuds レビュー",4.5),("review-airpods-pro2","🎧","ワイヤレスイヤホン","AirPods Pro 2 レビュー",4.8),("review-sony-wf1000xm5-sport","🎧","ワイヤレスイヤホン","Sony WF-SP910N レビュー",4.3)]},
    {"slug":"review-jblflip6","name":"JBL Flip 6","cat":"スピーカー","emoji":"🔊","price":"¥14,190","score":4.5,"bg":"#e65100,#bf360c","scores":[("音質",90,4.5),("防水",100,5.0),("コスパ",96,4.8),("バッテリー",90,4.5),("ポータビリティ",96,4.8)],"specs":[("出力","20W（ウーファー+ツィーター）"),("防水","IP67（水没1mまでOK）"),("バッテリー","12時間"),("接続","Bluetooth 5.1"),("重量","550g"),("特徴","PartyBoost（複数接続）")],"pros":["IP67で水没させても壊れない防水性","20W×2ウェイで音量・音質のバランス最良","12時間バッテリーで1日持つ","1.4万円の驚きのコスパ","JBL Connectで複数スピーカー同時再生"],"cons":["マイク通話には非対応","550gは小型スピーカーとしてやや重め","低温環境でバッテリー性能が落ちる"],"desc":"アウトドアスピーカーの王道JBL Flip 6。IP67防水×20W×12時間で1.4万円は市場最高コスパ。ビーチ・キャンプ・風呂場どこでも最高の音楽体験を。","related":[("review-sonysrsxb43","🔊","スピーカー","Sony SRS-XB43 レビュー",4.5),("review-marshallEmberton3","🔊","スピーカー","Marshall Emberton III レビュー",4.4),("review-boseSoundLinkMax","🔊","スピーカー","Bose SoundLink Max レビュー",4.7)]},
    {"slug":"review-boseSoundLinkMax","name":"Bose SoundLink Max","cat":"スピーカー","emoji":"🔊","price":"¥49,500","score":4.7,"bg":"#1a1a2e,#16213e","scores":[("音質",100,5.0),("防水",94,4.7),("バッテリー",92,4.6),("デザイン",96,4.8),("コスパ",80,4.0)],"specs":[("出力","最大音量クラス最大（非公開）"),("防水","IP67"),("バッテリー","20時間"),("充電","USB-C / ワイヤレス充電"),("接続","Bluetooth 5.3 / 3.5mm"),("特徴","ストラップ付属でどこでも持ち運べる")],"pros":["360°全方位サウンドが屋外でも豊かな音場","IP67防水でプールサイドでも使える","ワイヤレス充電対応（Qi）","20時間バッテリーで週末旅行も安心","Bose最強クラスのポータブル音質"],"cons":["5万円","重量が重め","USB-Cポートが1つのみ"],"desc":"ポータブルスピーカーの頂点に立つBose SoundLink Max。360°音場×IP67×20時間バッテリーで野外フェス・キャンプでも本格サウンド。音に妥協したくないアウトドア派へ。","related":[("review-sonysrsxb43","🔊","スピーカー","Sony SRS-XB43 レビュー",4.5),("review-jblflip6","🔊","スピーカー","JBL Flip 6 レビュー",4.5),("review-marshallEmberton3","🔊","スピーカー","Marshall Emberton III レビュー",4.4)]},
    {"slug":"review-fujifilmx100vi","name":"Fujifilm X100VI","cat":"カメラ","emoji":"📷","price":"¥279,500","score":4.9,"bg":"#2c2c2c,#1a1a1a","scores":[("フィルムシミュレーション",100,5.0),("コンパクト性",96,4.8),("画質",98,4.9),("デザイン",100,5.0),("コスパ",80,4.0)],"specs":[("センサー","APS-C 4020万画素 X-Trans CMOS 5 HR"),("レンズ","固定式 23mm F2"),("IBIS","最大6段ボディ内手ブレ補正"),("連写","20コマ/秒"),("動画","6.2K 30fps / 4K 60fps"),("重量","521g")],"pros":["6段IBISが固定レンズ機に革命をもたらした","フィルムシミュレーション20種類で撮って出しが最高","4020万画素×APS-Cの圧倒的解像度","521gを超えるコンパクトな本格カメラ","6.2K動画で映像制作にも対応"],"cons":["28万円","固定レンズでズーム不可","人気すぎて入手困難（品薄）","4K 60fpsはクロップあり"],"desc":"カメラ史上最も話題を呼んだ一台。フィルムの質感×最新センサー×6段IBISの三位一体。Instagramで撮って出しを共有したくなるフジフイルムの最高傑作。","related":[("review-fujifilmxt5","📷","カメラ","Fujifilm X-T5 レビュー",4.8),("review-sonyzve10ii","📷","カメラ","Sony ZV-E10 II レビュー",4.8),("review-canoneosr50","📷","カメラ","Canon EOS R50 レビュー",4.6)]},
    {"slug":"review-goprohero13black","name":"GoPro HERO13 Black","cat":"カメラ","emoji":"📷","price":"¥67,980","score":4.6,"bg":"#0d47a1,#1565c0","scores":[("アクション性能",100,5.0),("防水",100,5.0),("手ブレ補正",98,4.9),("バッテリー交換",96,4.8),("コスパ",82,4.1)],"specs":[("解像度","5.3K 60fps / 4K 120fps"),("防水","10m防水（ダイビングなし）"),("HyperSmooth","6.0（最高峰手ブレ補正）"),("バッテリー","交換可能式（Enduro）"),("接続","Bluetooth / Wi-Fi / USB-C"),("特徴","レンズMODシステム対応")],"pros":["HyperSmooth 6.0の手ブレ補正が映像をぬるぬるに","10m防水で水中撮影も問題なし","交換可能バッテリーで長時間撮影","レンズMODで広角・マクロ拡張可能","4K 120fpsのスローモーション"],"cons":["7万円","スマホカメラに比べて準備に手間がかかる","GoPro Subscriptionで本来のコスパが発揮される"],"desc":"アクションカメラの絶対王者HERO13。10m防水×HyperSmooth 6.0は他社の追随を許さない。スキー・サーフィン・ダイビング・バイクどんなシーンも最高の映像に。","related":[("review-insta360x4","📷","カメラ","Insta360 X4 レビュー",4.5),("review-djiosmoaction4","📷","カメラ","DJI Osmo Action 4 レビュー",4.6),("review-fujifilmx100vi","📷","カメラ","Fujifilm X100VI レビュー",4.9)]},
    {"slug":"review-galaxywatch7","name":"Samsung Galaxy Watch 7 44mm","cat":"スマートウォッチ","emoji":"⌚","price":"¥51,480","score":4.5,"bg":"#0d47a1,#1565c0","scores":[("健康センサー",96,4.8),("Galaxy AI",100,5.0),("Wear OS",90,4.5),("バッテリー",86,4.3),("コスパ",88,4.4)],"specs":[("チップ","Exynos W1000（3nm）"),("ディスプレイ","1.5インチ Super AMOLED"),("センサー","BioActive（心拍・血圧・体脂肪・睡眠）"),("バッテリー","40時間"),("防水","5ATM / IP68 / MIL規格"),("特徴","Galaxy AI健康コーチ")],"pros":["Galaxy AI健康コーチが運動・睡眠を分析","BioActivセンサーで体脂肪率まで計測","Wear OSでGoogle Mapなど全アプリ対応","5ATM＋MIL規格の高耐久性","Androidユーザーへの最高のスマートウォッチ"],"cons":["iPhoneとの連携は機能制限あり","40時間バッテリーはGarminに劣る","血圧機能は国内では要キャリブレーション"],"desc":"AndroidユーザーのベストスマートウォッチはGalaxy Watch 7。Galaxy AI健康コーチ×BioActivセンサーで健康管理が完全自動化される。Samsungスマホとの連携が特に優秀。","related":[("review-applewatchs10","⌚","スマートウォッチ","Apple Watch Series 10 レビュー",4.7),("review-garminvenu3","⌚","スマートウォッチ","Garmin Venu 3 レビュー",4.5),("review-pixelwatch3","⌚","スマートウォッチ","Pixel Watch 3 レビュー",4.5)]},
    {"slug":"review-dellalienware34oled","name":"Dell Alienware 34 QD-OLED","cat":"モニター","emoji":"🖥️","price":"¥169,800","score":4.8,"bg":"#0d0d0d,#1a0a1a","scores":[("ゲーム性能",100,5.0),("QD-OLED画質",100,5.0),("湾曲体験",98,4.9),("応答速度",100,5.0),("コスパ",80,4.0)],"specs":[("パネル","QD-OLED 3440×1440 165Hz"),("サイズ","34インチ湾曲（1800R）"),("応答速度","0.1ms GtG"),("HDR","DisplayHDR True Black 400"),("接続","HDMI 2.1×2 / DP 1.4×1 / USB-C"),("特徴","Alienware Cherry MX タクタイルホイール")],"pros":["QD-OLEDの圧倒的黒表現と色彩","34インチ湾曲でゲームへの没入感が最大","0.1ms GtGの超高速応答","DisplayHDR True Black 400でHDR映像が映える","HDMI 2.1×2でPS5とPC同時接続"],"cons":["17万円","重量が重く設置後の移動が大変","OLEDの焼き付きリスク（長時間静止画に注意）"],"desc":"ゲーミングモニターの最高峰。QD-OLED×34インチ湾曲×165Hzは完全な別次元の没入体験を提供する。PCゲームに本気で投資するなら最終的にここに辿り着く。","related":[("review-asusrogswiftpg279qm","🖥️","モニター","ASUS ROG Swift PG279QM レビュー",4.7),("review-lg27gp850b","🖥️","モニター","LG 27GP850B レビュー",4.6),("review-sonyinzone-m9ii","🖥️","PC周辺機器","Sony INZONE M9 II レビュー",4.7)]},
    {"slug":"review-lgultrafine5k27md5kl","name":"LG UltraFine 5K Display 27MD5KL","cat":"モニター","emoji":"🖥️","price":"¥99,800","score":4.6,"bg":"#1a1a2e,#16213e","scores":[("5K解像度",100,5.0),("Mac連携",100,5.0),("Thunderbolt",100,5.0),("コスパ",74,3.7),("色精度",92,4.6)],"specs":[("解像度","5120×2880（5K）"),("パネル","IPS 218ppi"),("接続","Thunderbolt 3（94W給電）"),("カメラ","内蔵1080pカメラ×マイク×スピーカー"),("サイズ","27インチ"),("特徴","Apple推奨モニター")],"pros":["5K解像度でMacBookの画面を5倍の面積に","Thunderbolt 3×1本で映像+94W給電+データ転送","Mac UIが5Kで完璧にシャープ","内蔵カメラ・マイク・スピーカーでケーブル1本完結","Apple公式推奨モニター"],"cons":["10万円","Windowsでの5K出力は対応PC限定","ゲームには不向き（60Hzまで）","スタンドの調節範囲が狭い"],"desc":"MacBookユーザーの最終到達点。Thunderbolt 3一本で5K映像+94W充電を実現し、机上をケーブルフリーに。MacBookの性能を最大限に引き出すApple公認モニター。","related":[("review-benqpd3205u","🖥️","モニター","BenQ PD3205U レビュー",4.6),("review-asusproadart27","🖥️","モニター","ASUS ProArt PA27UCX-K レビュー",4.7),("review-dellu2723d","🖥️","モニター","Dell U2723D レビュー",4.7)]},
    {"slug":"review-lg-oled-c4","name":"LG OLED65C4 65インチ","cat":"テレビ","emoji":"📺","price":"¥269,800","score":4.9,"bg":"#0d0d0d,#1a1a1a","scores":[("OLED画質",100,5.0),("ゲーミング機能",100,5.0),("HDR",100,5.0),("WebOS",94,4.7),("コスパ",82,4.1)],"specs":[("パネル","OLED evo 65インチ 4K 120Hz"),("プロセッサー","α9 AI Processor Gen7"),("ゲーミング","HDMI 2.1×4 / VRR / G-Sync / FreeSync"),("HDR","Dolby Vision IQ / HDR10 / HLG"),("応答速度","0.1ms"),("特徴","Dolby Atmos / AI 4K アップスケーリング")],"pros":["OLED evoの完璧な黒表現と無限コントラスト","HDMI 2.1×4でPS5・Xbox・PC全部4K 120fps","0.1ms応答速度でゲームが超滑らか","α9 Gen7 AIでアップスケーリングが完璧","Dolby Vision IQ×Dolby Atmosで映画が最高"],"cons":["27万円","OLEDの焼き付きリスク（静止画に注意）","壁掛け工事が必要なケースも"],"desc":"テレビ界の頂点LG OLED C4。映画・ゲーム・スポーツ全てが完璧な画質で楽しめる究極のリビングシアター。HDMI 2.1×4はゲーマーにとって夢のスペック。","related":[("review-sony-bravia-xr-a95l","📺","テレビ","Sony BRAVIA XR A95L レビュー",4.8),("review-samsung-neo-qled","📺","テレビ","Samsung Neo QLED レビュー",4.7),("review-hisense-u9n","📺","テレビ","Hisense U9N レビュー",4.5)]},
    {"slug":"review-sonos-arc-ultra","name":"Sonos Arc Ultra","cat":"サウンドバー","emoji":"🔊","price":"¥139,800","score":4.8,"bg":"#1a1a1a,#2d2d2d","scores":[("Dolby Atmos",100,5.0),("音質",100,5.0),("デザイン",100,5.0),("Trueplay自動調整",100,5.0),("コスパ",76,3.8)],"specs":[("チャンネル","9.1.4（9スピーカー内蔵）"),("Dolby Atmos","対応（高さ表現）"),("接続","HDMI eARC / HDMI / Wi-Fi / AirPlay 2"),("特徴","Sound Motion技術 / Trueplay自動調整"),("サイズ","W114.2cm × H8.7cm"),("特徴2","Sonos S2アプリ対応")],"pros":["9スピーカーによる本物の立体音響","Trueplayが部屋の形状に自動最適化","AirPlay 2でiPhoneから直接ストリーミング","デザインがリビングに完璧に馴染む","Sonosエコシステムで家中の音楽をコントロール"],"cons":["14万円","サブウーファーは別売り","eARCがないTV では機能制限あり"],"desc":"ホームシアターの頂点Sonos Arc Ultra。9スピーカー×Dolby Atmos×Trueplay自動調整でリビングをコンサートホールに変える。音楽・映画どちらも最高の体験を提供。","related":[("review-bose-smart-soundbar-900","🔊","サウンドバー","Bose Smart Soundbar 900 レビュー",4.7),("review-yamaha-yas-209","🔊","サウンドバー","Yamaha YAS-209 レビュー",4.4),("review-samsung-hw-q990d","🔊","サウンドバー","Samsung HW-Q990D レビュー",4.6)]},
    {"slug":"review-dyson-airwrap-multi","name":"Dyson Airwrap Multi-Styler Complete","cat":"ドライヤー","emoji":"💨","price":"¥79,800","score":4.8,"bg":"#cc5500,#993d00","scores":[("スタイリング多機能",100,5.0),("髪へのやさしさ",100,5.0),("仕上がり",98,4.9),("時短性能",94,4.7),("コスパ",72,3.6)],"specs":[("技術","コアンダ効果で風が髪を巻きつける"),("アタッチメント","8種類（カール・ストレート・乾燥）"),("温度","高温なし（熱ダメージゼロ設計）"),("電源","AC 100V 50/60Hz"),("重量","730g（本体）"),("特徴","Dyson Supersonic技術応用")],"pros":["高温を使わないのでカラー毛でもダメージゼロ","1台でカール・ウェーブ・ストレート・乾燥が全部できる","コアンダ効果で自然なカールが超簡単","美容院レベルの仕上がりが自宅で再現","プレミアムな所有体験・インスタ映え"],"cons":["8万円","730gの本体重量で疲れやすい","慣れるまでに練習が必要","長毛の全体乾燥はドライヤーの方が速い"],"desc":"ヘアスタイリングの常識を変えたDyson Airwrap。高熱を使わずカール・ストレートが自宅で完成。美容院代×時間コストを考えると8万円は安い投資。","related":[("review-dyson-supersonic","💨","ドライヤー","Dyson Supersonic レビュー",4.8),("review-panasonic-nanoe-dryer","💨","ドライヤー","Panasonic ナノケア EH-NA0J レビュー",4.7),("review-shark-speedstyle","💨","ドライヤー","SHARK SpeedStyle レビュー",4.5)]},
    {"slug":"review-nespresso-vertuo-next","name":"Nespresso Vertuo Next","cat":"コーヒーメーカー","emoji":"☕","price":"¥19,800","score":4.4,"bg":"#3e2723,#4e342e","scores":[("コーヒー品質",92,4.6),("手軽さ",100,5.0),("カプセル種類",96,4.8),("コスパ",82,4.1),("デザイン",90,4.5)],"specs":[("技術","遠心力抽出（Centrifusion）"),("対応カプセル","Vertuo専用（5サイズ対応）"),("カップサイズ","Espresso〜Alto（80ml〜414ml）"),("予熱","15秒"),("重量","2.7kg"),("特徴","NFC認識でカプセル自動設定")],"pros":["NFCでカプセルを読み取り自動最適化","エスプレッソからアメリカンまで1台で対応","15秒予熱で忙しい朝でも即コーヒー","100種類以上のカプセルから選べる","2万円のコスパ"],"cons":["1杯のカプセルコストが高め（約100円/杯）","Vertuo専用カプセルのみ対応","Original Lineのカプセルは非対応","サイズは他のマシンよりコンパクトではない"],"desc":"毎朝のコーヒーをカフェクオリティに変える最も手軽なコーヒーメーカー。NFC自動認識×15秒予熱でボタン一押しの最高の一杯。カプセル代を含めても外で飲むより安い。","related":[("review-delonghi-dedica","☕","コーヒーメーカー","De'Longhi Dedica EC685 レビュー",4.6),("review-siroca-sc-c111","☕","コーヒーメーカー","シロカ全自動SC-C111 レビュー",4.3),("review-melitta-aroma-fresh","☕","コーヒーメーカー","Melitta アロマフレッシュ レビュー",4.2)]},
    {"slug":"review-irobot-roomba-j9plus","name":"iRobot Roomba j9+","cat":"ロボット掃除機","emoji":"🤖","price":"¥179,800","score":4.7,"bg":"#1a237e,#283593","scores":[("ゴミ自動収集",100,5.0),("障害物回避",100,5.0),("清掃能力",96,4.8),("アプリ連携",94,4.7),("コスパ",76,3.8)],"specs":[("吸引力","PerfectEdge × 3D Detect"),("自動収集","Clean Base（60日分収集）"),("障害物検知","iRobot OS 8.0 × AI障害物回避"),("マッピング","Imprint Smart Mapping 3D"),("充電","自動帰還充電"),("対応","Alexa / Google Assistant")],"pros":["60日間のゴミ収集でゴミ捨て不要","靴下・コードを避けるAI障害物回避","3Dマッピングで間取りを完全記憶","「このエリアだけ掃除」の細かい指示が可能","Amazonセール時のコスパ向上"],"cons":["18万円","本体が大きく狭い場所は苦手","モップ機能なし（掃除のみ）","消耗品（フィルター・ブラシ）の定期交換が必要"],"desc":"ロボット掃除機の王者iRobot Roomba j9+。AI障害物回避×60日自動ゴミ収集で掃除の手間がほぼゼロに。子育て家族・ペット家庭に特におすすめの究極の時間節約家電。","related":[("review-roborock-s8-pro-ultra","🤖","ロボット掃除機","Roborock S8 Pro Ultra レビュー",4.8),("review-eufyrobovacx8","🤖","ロボット掃除機","Eufy RoboVac X8 レビュー",4.4),("review-ecovacs-deebot-t30s","🤖","ロボット掃除機","Ecovacs DEEBOT T30S レビュー",4.5)]},
    {"slug":"review-ninja-speedi","name":"Ninja Speedi 急速調理器 ON400J","cat":"調理家電","emoji":"🍳","price":"¥29,800","score":4.6,"bg":"#212121,#424242","scores":[("調理速度",100,5.0),("多機能性",100,5.0),("コスパ",92,4.6),("使いやすさ",90,4.5),("後片付け",86,4.3)],"specs":[("調理方式","急速蒸し調理＋エアフライ＋炒める＋煮る"),("容量","5.7L"),("調理時間","最短15分で完成"),("電力","1750W"),("重量","4.1kg"),("付属品","コンビクックトレー付属")],"pros":["15分で完成する「急速調理」が仕事帰りに最強","エアフライで揚げ物がヘルシーに作れる","蒸し・炒め・煮込みが1台で全部対応","炊飯器・電子レンジ・鍋を全部置き換えられる","Ninja公式レシピアプリで料理初心者でも安心"],"cons":["4.1kgとやや重い","容量5.7Lは2人暮らしまでが最適","洗い物が複数パーツある"],"desc":"忙しい現代人のための究極の時短調理家電。帰宅後15分でメイン＋副菜が同時完成。一人暮らし・共働き家庭で「料理時間ゼロ」を実現する魔法の調理器。","related":[("review-panasonic-bistro","🍳","調理家電","Panasonic ビストロ レビュー",4.5),("review-philips-airfryer","🍳","調理家電","Philips ノンフライヤー レビュー",4.4),("review-balumu-slow-cooker","🍳","調理家電","Balumu スロークッカー レビュー",4.1)]},
    {"slug":"review-secretlab-titan-evo","name":"Secretlab TITAN Evo 2022","cat":"ゲーミングチェア","emoji":"🪑","price":"¥74,800","score":4.8,"bg":"#1a1a1a,#0d0d0d","scores":[("座り心地",100,5.0),("腰サポート",100,5.0),("耐久性",98,4.9),("デザイン",96,4.8),("コスパ",84,4.2)],"specs":[("素材","NEO™ ハイブリッドレザー（または SoftWeave®）"),("リクライニング","最大165°"),("腰サポート","マグネット着脱式ランバーサポート"),("アームレスト","4Dアームレスト"),("耐荷重","130kg"),("特徴","キャスター交換可能・ISOセーフティ認定")],"pros":["着脱式ランバーサポートが腰痛ゲーマーを救う","165°リクライニングで仮眠も快適","NEOハイブリッドレザーが通気性とケアのバランス最高","4Dアームレストで肩こり改善","3年保証の耐久性"],"cons":["7.5万円","重量が重く組み立てが大変","カラーバリエーションが限られる"],"desc":"ゲーミングチェア市場の王者Secretlab TITAN Evo。腰痛持ちゲーマーが最終的に選ぶ一脚。マグネット式ランバーサポート×4Dアームレストで長時間プレイの疲労を激減させる。","related":[("review-akracing-pro-x","🪑","ゲーミングチェア","AKRacing Pro-X V2 レビュー",4.6),("review-gtrace-gc900","🪑","ゲーミングチェア","GT RACING GC900 レビュー",4.3),("review-noblechairs-hero","🪑","ゲーミングチェア","noblechairs HERO レビュー",4.5)]},
    {"slug":"review-tplink-deco-be65","name":"TP-Link Deco BE65","cat":"ネットワーク機器","emoji":"📡","price":"¥39,800","score":4.6,"bg":"#1b5e20,#2e7d32","scores":[("Wi-Fi 7速度",100,5.0),("メッシュ安定性",98,4.9),("設定簡単さ",96,4.8),("コスパ",90,4.5),("セキュリティ",92,4.6)],"specs":[("規格","Wi-Fi 7（IEEE 802.11be）"),("速度","最大BE19000（理論値）"),("バンド","2.4GHz + 5GHz + 6GHz（トライバンド）"),("接続台数","推奨200台まで"),("設定","Decoアプリ5分設定"),("特徴","HomeShield セキュリティ（保護者フィルタリング）")],"pros":["Wi-Fi 7の6GHz帯で実測2Gbps超を実現","Decoアプリ5分で誰でもメッシュ構築","200台接続でスマートホーム大量機器に対応","HomeShieldで子どものネット利用制限","2台セットで家全体をカバー"],"cons":["4万円","Wi-Fi 7対応デバイスが必要（後方互換あり）","ISPが6GHz対応かの確認が必要"],"desc":"家全体を超高速Wi-Fi 7でカバーするメッシュルーター。6GHz帯×実測2Gbps超×200台接続で未来のスマートホームに完全対応。設定5分の手軽さも◎。","related":[("review-eero-pro-6e","📡","ネットワーク機器","Amazon eero Pro 6E レビュー",4.5),("review-asus-zenwifi-pro-et12","📡","ネットワーク機器","ASUS ZenWiFi Pro ET12 レビュー",4.6),("review-netgear-orbi-rbk863s","📡","ネットワーク機器","Netgear Orbi RBK863S レビュー",4.7)]},
    {"slug":"review-benq-tk700sti","name":"BenQ TK700STi","cat":"プロジェクター","emoji":"📽️","price":"¥149,800","score":4.6,"bg":"#0d1b2a,#1b263b","scores":[("4K画質",96,4.8),("短焦点",100,5.0),("ゲーミング",98,4.9),("ストリーミング",94,4.7),("コスパ",86,4.3)],"specs":[("解像度","4K UHD（3840×2160）"),("輝度","3000ルーメン"),("焦点距離","短焦点（1.2:1）"),("遅延","4K@60fps: 16ms / 1080p@240fps: 4ms"),("OS","Android TV 9.0"),("HDR","HDR-PRO / HLG")],"pros":["16msの低遅延で4Kゲームが快適","短焦点1.2:1で2m未満から100インチ投影","3000ルーメンで明るい部屋でも映る","Android TV内蔵でNetflix・YouTube直接視聴","PS5・Xbox Series Xのゲームが4K×大画面で楽しめる"],"cons":["15万円","スピーカーは内蔵だが迫力は控えめ","4K 120Hzは非対応（60Hzまで）"],"desc":"リビングシアターとゲームを両立する短焦点4Kプロジェクター。2m未満から100インチ投影×16ms低遅延でPS5ゲームを大画面で。Android TV内蔵で別途デバイス不要。","related":[("review-epson-ehtw7500","📽️","プロジェクター","Epson EH-TW7500 レビュー",4.5),("review-lg-cinebeam-hu715q","📽️","プロジェクター","LG CineBeam HU715Q レビュー",4.7),("review-xgimi-horizon-ultra","📽️","プロジェクター","XGIMI Horizon Ultra レビュー",4.5)]},
    {"slug":"review-epson-ehtw7500","name":"Epson EH-TW7500","cat":"プロジェクター","emoji":"📽️","price":"¥119,800","score":4.5,"bg":"#1a237e,#283593","scores":[("4K画質",94,4.7),("明るさ",96,4.8),("コスパ",90,4.5),("ホーム映画",96,4.8),("設置柔軟性",88,4.4)],"specs":[("解像度","4K PRO-UHD（画素ずらし）"),("輝度","2800ルーメン"),("コントラスト","200,000:1"),("レンズシフト","垂直96%／水平47%"),("HDR","HDR10 / HLG"),("3D","対応")],"pros":["12万円でフル4K投影の圧倒的コスパ","2800ルーメンで昼間でも映画鑑賞可能","レンズシフトで設置場所が柔軟","200,000:1コントラストの深みある黒","3D投影対応"],"cons":["短焦点ではないため設置距離が必要","Apple TV・Amazonスティックなど別途デバイスが必要","ランプ交換の維持コスト"],"desc":"12万円で本格4Kホームシアターを実現するコスパ最強プロジェクター。2800ルーメン×レンズシフト自由度の高さで設置場所を選ばない。週末は自宅を映画館に変えよう。","related":[("review-benq-tk700sti","📽️","プロジェクター","BenQ TK700STi レビュー",4.6),("review-lg-cinebeam-hu715q","📽️","プロジェクター","LG CineBeam HU715Q レビュー",4.7),("review-xgimi-horizon-ultra","📽️","プロジェクター","XGIMI Horizon Ultra レビュー",4.5)]},
'''

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

MARKER = '    {"slug":"review-boseqc45"'
if MARKER not in content:
    print("ERROR: marker not found")
    exit(1)

new_content = content.replace(MARKER, NEW_PRODUCTS + MARKER, 1)

with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)

# Count products
import re
slugs = re.findall(r'"slug":"review-', new_content)
print(f"Total products: {len(slugs)}")
print("Done!")
